/* Generated by Opal 0.9.2 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var OPAL_CONFIG = { method_missing: true, arity_check: false, freezing: true, tainting: true };
  var $a, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $klass = Opal.klass, $range = Opal.range, postcode = nil, blokouderling = nil;

  Opal.add_stubs(['$require', '$include', '$attr_reader', '$delete', '$upcase', '$[]', '$==', '$numbers', '$<=>', '$letters', '$new', '$gsub', '$value', '$find', '$between?', '$puts']);
  self.$require("opal");
  self.$require("opal-jquery");
  (function($base, $super) {
    function $Postcode(){};
    var self = $Postcode = $klass($base, $super, 'Postcode', $Postcode);

    var def = self.$$proto, $scope = self.$$scope;

    def.postcode = nil;
    self.$include($scope.get('Comparable'));

    self.$attr_reader("numbers", "letters");

    Opal.defn(self, '$initialize', function(postcode) {
      var self = this;

      self.postcode = postcode.$upcase().$delete(" ");
      self.numbers = self.postcode['$[]']($range(0, 3, false));
      return self.letters = self.postcode['$[]']($range(4, 5, false));
    });

    return (Opal.defn(self, '$<=>', function(other) {
      var $a, self = this;

      if ((($a = (self.$numbers()['$=='](other.$numbers()))) !== nil && (!$a.$$is_boolean || $a == true))) {
        return self.$letters()['$<=>'](other.$letters())
        } else {
        return self.$numbers()['$<=>'](other.$numbers())
      };
    }), nil) && '<=>';
  })($scope.base, null);
  postcode = $scope.get('Postcode').$new($scope.get('Element').$find("#postcode_id").$value().$upcase().$gsub(/ /, ""));
  blokouderling = (function() {if ((($a = postcode['$between?']($scope.get('Postcode').$new("2801AA"), $scope.get('Postcode').$new("2801AS"))) !== nil && (!$a.$$is_boolean || $a == true))) {return "Blok B1, ouderling NN"}else if ((($a = postcode['$between?']($scope.get('Postcode').$new("2801AT"), $scope.get('Postcode').$new("2801AT"))) !== nil && (!$a.$$is_boolean || $a == true))) {return "Blok B6, ouderling NN"}else if ((($a = postcode['$between?']($scope.get('Postcode').$new("2801AV"), $scope.get('Postcode').$new("2801BA"))) !== nil && (!$a.$$is_boolean || $a == true))) {return "Blok B1, ouderling NN"}else if ((($a = postcode['$between?']($scope.get('Postcode').$new("2801BX"), $scope.get('Postcode').$new("2801BZ"))) !== nil && (!$a.$$is_boolean || $a == true))) {return "Blok B6, ouderling NN"}else if ((($a = postcode['$between?']($scope.get('Postcode').$new("2801AT"), $scope.get('Postcode').$new("2801AT"))) !== nil && (!$a.$$is_boolean || $a == true))) {return "Blok B6, ouderling NN"}else if ((($a = postcode['$between?']($scope.get('Postcode').$new("2801CA"), $scope.get('Postcode').$new("2801CH"))) !== nil && (!$a.$$is_boolean || $a == true))) {return "Blok B6, ouderling NN"}else {return "none"}})();
  return self.$puts(blokouderling);
})(Opal);
