/* Generated by Opal 0.9.2 */
(function (Opal) {
    Opal.dynamic_require_severity = "error";
    var OPAL_CONFIG = {method_missing: true, arity_check: false, freezing: true, tainting: true};
    var $a, $b, TMP_1, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, postcode = nil;

    Opal.add_stubs(['$require', '$ready?', '$text=', '$find', '$puts', '$gsub', '$upcase', '$value']);
    self.$require("opal");
    self.$require("opal-jquery");
    ($a = ($b = $scope.get('Document'))['$ready?'], $a.$$p = (TMP_1 = function () {
        var self = TMP_1.$$s || this, $a, $b;

        return (($a = ["Opal is loaded"]), $b = $scope.get('Element').$find("#foo"), $b['$text='].apply($b, $a), $a[$a.length - 1])
    }, TMP_1.$$s = self, TMP_1), $a).call($b);
    self.$puts("Hi from Ruby");
    postcode = $scope.get('Element').$find("#postcode_id").$value().$upcase().$gsub(/ /, "");
    return self.$puts(postcode);
})(Opal);
